server:
  port: 7778
spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/customer?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
customer:
  allow-get-customer: true