server:
  port: 7777
spring:
  name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accounts?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    accounts:
      allow-get-accounts: true
