server:
  port: 7777
spring:
  datasource:
    password: 1234
    url: "jdbc:mysql://localhost:3306/accounts?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true"
    username: root
  jpa:
    accounts:
      allow-get-accounts: true
    hibernate:
      ddl-auto: update
  name: accounts

