server:
  port: 7777
accounts:
  datasource:
    url: jdbc:mysql://localhost:3306/accounts?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true
    username: root
    password:
    ddl-auto: update
  allow-get-accounts: true



