accounts:
  allow-get-accounts: true
  datasource:
    ddl-mode: update
    password: 1234
    url: jdbc:mysql://localhost:3306/accounts?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true
    username: root
server:
  port: 7777

